"""Initial schema

Revision ID: 120a2dcd871c
Revises:
Create Date: 2026-04-17 13:46:50.068643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "120a2dcd871c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SPECIAL_PRODUCT",
                "WEAPONS",
                "ARMOR",
                "ACCESSORIES",
                "INSTRUMENT",
                "COSTUME",
                "CONSUMABLES",
                "CRAFTING",
                "MACHINING",
                "COMPANIONS",
                "OTHER",
                "LUNAGEM",
                "LUNASTONE",
                name="itemcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "grade",
            sa.Enum(
                "ALL",
                "GRAND",
                "RARE",
                "ARCANE",
                "HEROIC",
                "UNIQUE",
                "CELESTIAL",
                "DIVINE",
                "EPIC",
                "LEGENDARY",
                "MYTHIC",
                "ETERNAL",
                name="itemgrade",
            ),
            nullable=False,
        ),
        sa.Column("current_price", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_category"), "item", ["category"], unique=False)
    op.create_index(op.f("ix_item_grade"), "item", ["grade"], unique=False)
    op.create_index(op.f("ix_item_name"), "item", ["name"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "pricepoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricepoint_captured_at"), "pricepoint", ["captured_at"], unique=False
    )
    op.create_index(
        op.f("ix_pricepoint_item_id"), "pricepoint", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_pricepoint_source"), "pricepoint", ["source"], unique=False
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True
        ),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_user_id"), "profile", ["user_id"], unique=True)
    op.create_table(
        "useritem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_user_item"),
    )
    op.create_index(op.f("ix_useritem_item_id"), "useritem", ["item_id"], unique=False)
    op.create_index(op.f("ix_useritem_user_id"), "useritem", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_useritem_user_id"), table_name="useritem")
    op.drop_index(op.f("ix_useritem_item_id"), table_name="useritem")
    op.drop_table("useritem")
    op.drop_index(op.f("ix_profile_user_id"), table_name="profile")
    op.drop_table("profile")
    op.drop_index(op.f("ix_pricepoint_source"), table_name="pricepoint")
    op.drop_index(op.f("ix_pricepoint_item_id"), table_name="pricepoint")
    op.drop_index(op.f("ix_pricepoint_captured_at"), table_name="pricepoint")
    op.drop_table("pricepoint")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_item_name"), table_name="item")
    op.drop_index(op.f("ix_item_grade"), table_name="item")
    op.drop_index(op.f("ix_item_category"), table_name="item")
    op.drop_table("item")
    # ### end Alembic commands ###
