"""item_uniqueness_and_last_price_at

Revision ID: 4fd5cb5331bb
Revises: 79bf2c351107
Create Date: 2026-05-19 15:47:50.684287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4fd5cb5331bb"
down_revision: Union[str, Sequence[str], None] = "79bf2c351107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("last_price_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint("uq_item_name_grade", "item", ["name", "grade"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_item_name_grade", "item", type_="unique")
    op.drop_column("item", "last_price_at")
    # ### end Alembic commands ###
