"""add_user_inventory

Revision ID: 79bf2c351107
Revises: a1b2c3d4e5f6
Create Date: 2026-05-19 14:48:38.904382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79bf2c351107"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userinventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_user_inventory"),
    )
    op.create_index(
        op.f("ix_userinventory_item_id"), "userinventory", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_userinventory_user_id"), "userinventory", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userinventory_user_id"), table_name="userinventory")
    op.drop_index(op.f("ix_userinventory_item_id"), table_name="userinventory")
    op.drop_table("userinventory")
    # ### end Alembic commands ###
