"""add recipe and recipeingredient tables

Revision ID: d23b9a1d1e22
Revises: 120a2dcd871c
Create Date: 2026-05-15 19:50:41.088686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23b9a1d1e22'
down_revision: Union[str, Sequence[str], None] = '120a2dcd871c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('output_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_item_id'), 'recipe', ['item_id'], unique=True)
    op.create_table('recipeingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'ingredient_item_id', name='uq_recipe_ingredient')
    )
    op.create_index(op.f('ix_recipeingredient_ingredient_item_id'), 'recipeingredient', ['ingredient_item_id'], unique=False)
    op.create_index(op.f('ix_recipeingredient_recipe_id'), 'recipeingredient', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipeingredient_recipe_id'), table_name='recipeingredient')
    op.drop_index(op.f('ix_recipeingredient_ingredient_item_id'), table_name='recipeingredient')
    op.drop_table('recipeingredient')
    op.drop_index(op.f('ix_recipe_item_id'), table_name='recipe')
    op.drop_table('recipe')
    # ### end Alembic commands ###
